[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4.0.29", features = ["derive"] }
log = "0.4"
fern = "0.6"

[features]
sample = []
